config/routes.rb
Rails.application.routes.draw do

  # 顧客用

  scope module: :public do
    # customers
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    get "customers/my_page" => "customers#show"
    resource :customers, only: [:edit, :update]

    # homes
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    # items
    resources :items, only: [:index, :show]

    # cart_items
    delete "cart_items/all_destroy" => "cart_items#all_destroy"
    resources :cart_items, only: [:index, :update, :create, :destroy]

    # orders
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/finish' => 'orders#finish'
    resources :orders, only: [:index, :show, :new, :create]

    # addresses
    resources :addresses, only: [:index, :create, :destroy, :update, :edit]

  end

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



  # 管理者用

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # homes
    get '/' => 'homes#top'

    # cunstomers
    resources :customers, only: [:index, :show, :edit, :update]

    # items
    resources :items, except: [:destroy]

    # genres
    resources :genres, only: [:index, :create, :edit, :update]

    # orders
    resources :orders, only: [:show, :update]

    # order_details
    resources :order_details, only: [:update]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre

  with_options presence: true do
    validates :image
    validates :name
    validates :introduction
    validates :tax_excluded_price
    validates :sales_status
    validates :genre_id
  end

  validates :tax_excluded_price, numericality: {greater_than: 50}

  def tax_included_price
    (tax_excluded_price * 1.1).floor
  end

  enum sales_status: { sale: true, stop_selling: false }

  def get_item_image(size)
    image.variant(resize: size).processed
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = '商品を登録しました'
      redirect_to admin_item_path(@item)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = '商品の情報を更新しました'
      redirect_to admin_item_path(@item)
    else
      render 'edit'
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :tax_excluded_price, :sales_status, :genre_id, :image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class='container'>
  <div class='row'>
    <h3 class="mini-title">商品編集</h3>
  </div
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render "layouts/errors", obj: @item %>
      <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true do |f| %>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">商品画像</label>
          <div class="col-md-9">
            <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">商品名</label>
          <div class="col-md-9">
            <%= f.text_field :name, placeholder: "商品名", class: 'form-control item_name' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">商品説明</label>
          <div class="col-md-9">
            <%= f.text_area :introduction, size: "100x5", placeholder: "ここに説明文を記述します", class: 'form-control item_introduction' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">ジャンル</label>
          <div class="col-md-9">
            <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class: 'form-control item_genre_id' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">税抜価格</label>
          <div class="col-md-9  d-flex flex-row">
            ￥<%= f.text_field :tax_excluded_price, placeholder: "1000", class: 'form-control item_tax_excluded_price' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :販売ステータス %>
          <%= f.radio_button :sales_status, Item.sales_statuses.key(true) %>
          <%= f.label :sales_status, Item.sales_statuses_i18n[:sale] %>
          <%= f.radio_button :sales_status, Item.sales_statuses.key(false) %>
          <%= f.label :sales_status, Item.sales_statuses_i18n[:stop_selling] %>
        </div>
        <div class="form-group" align="center">
          <%= f.submit "変更を保存",class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="mini-title">商品一覧</h3>
    <div class="icon ml-auto">
      <%= link_to  new_admin_item_path, style:"font-size:40px;" do %>
        <i class="fas fa-plus-circle" style="color: green;"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr class="table-secondary">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><strong><%= link_to item.name, admin_item_path(item.id), class: "text-dark" %></strong></td>
            <td>￥<%= item.tax_included_price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.sales_status_i18n == "販売中" %>
                <b class="text-success"><%= item.sales_status_i18n %></b>
              <% else %>
                <b class="text-danger"><%= item.sales_status_i18n %></b>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @items, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/items/new.html.erb
<div class='container'>
  <div class='row'>
    <h3 class="mini-title">商品新規登録</h3>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <% if @item.errors.any? %>
        <%= @item.errors.count %>件のエラーが発生しました
        <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @item, url: admin_items_path do |f| %>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">商品画像</label>
          <div class="col-md-9">
            <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">商品名</label>
          <div class="col-md-9">
            <%= f.text_field :name, placeholder: "商品名", class: 'form-control item_name' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">商品説明</label>
          <div class="col-md-9">
            <%= f.text_area :introduction, size: "100x5", placeholder: "ここに説明文を記述します", class: 'form-control item_introduction' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">ジャンル</label>
          <div class="col-md-9">
            <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class: 'form-control item_genre_id' %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-3 col-form-label">税抜価格</label>
          <div class="col-md-9 d-flex flex-row">
            <span>￥</span><%= f.text_field :tax_excluded_price, placeholder: "1000", class: 'form-control item_tax_excluded_price' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :販売ステータス %>
          <%= f.radio_button :sales_status, Item.sales_statuses.key(true) %>
          <%= f.label :sales_status, Item.sales_statuses_i18n[:sale] %>
          <%= f.radio_button :sales_status, Item.sales_statuses.key(false) %>
          <%= f.label :sales_status, Item.sales_statuses_i18n[:stop_selling] %>
        </div>
        <div class="form-group" align="center">
          <%= f.submit "新規登録", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h2 class="mini-title">商品詳細</h2>
  </div>
  <div class="row">
    <div class="col-3 offset-1">
      <%= image_tag @item.image, class: "show-img" %>
    </div>
    <div class="col-5 offset-2">
      <table class="table">
        <tbody>
          <tr>
            <td><h6>商品名</h6></td>
            <td><h5><b><%= @item.name %></b></h5></td>
          </tr>
          <tr>
            <td><h6>商品説明</h6></td>
            <td><p><%= @item.introduction %></p></td>
          </tr>
          <tr>
            <td><h6>ジャンル</h6></td>
            <td><b><%= @item.genre.name %></b></td>
          </tr>
          <tr>
            <td>税込価格<br>(税抜価格)</td>
            <td>
              <h5>
                ￥<%= @item.tax_included_price.to_s(:delimited) %>
                (<%= @item.tax_excluded_price.to_s(:delimited) %>)
              </h5>
            </td>
          </tr>
          <tr>
            <td><h6>販売ステータス</h6></td>
            <td>
              <% if @item.sales_status_i18n == "販売中" %>
                <b class="text-success"><%= @item.sales_status_i18n %></b>
              <% else %>
                <b class="text-danger"><%= @item.sales_status_i18n %></b>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="col-5 offset-2 text-center">
        <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
      </div>
    </div>
  </div>