config/routes.rb
Rails.application.routes.draw do

  # 顧客用

  scope module: :public do
    # customers
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    get "customers/my_page" => "customers#show"
    resource :customers, only: [:edit, :update]

    # homes
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    # items
    resources :items, only: [:index, :show]

    # cart_items
    delete "cart_items/all_destroy" => "cart_items#all_destroy"
    resources :cart_items, only: [:index, :update, :create, :destroy]

    # orders
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/finish' => 'orders#finish'
    resources :orders, only: [:index, :show, :new, :create]

    # addresses
    resources :addresses, only: [:index, :create, :destroy, :update, :edit]

  end

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



  # 管理者用

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # homes
    get '/' => 'homes#top'

    # cunstomers
    resources :customers, only: [:index, :show, :edit, :update]

    # items
    resources :items, except: [:destroy]

    # genres
    resources :genres, only: [:index, :create, :edit, :update]

    # orders
    resources :orders, only: [:show, :update]

    # order_details
    resources :order_details, only: [:update]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  # has_many :itmes, through: :cart_items
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :phone_number, presence: true
  validates :post_code, length: { is: 7 }
  # 退会済ユーザーをブロック
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def address_display_code
    '〒' + post_code + '' + address + '' + last_name + '' + first_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path, notice: "更新に成功しました"
    else
      render "edit"
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="mb-5">
  <h3 class="ml-5 mini-title"><%= @customer.last_name+@customer.first_name %>さんの会員情報編集</h3>
</div>

<div class="px-5 mx-5 row">
  <div class="col-9">
    <%= render "layouts/errors", obj: @customer %>
    <%= form_with model:@customer, url: admin_customer_path(@customer), method: :patch do |f| %>
      <div class="form-group row">
        <label class="col-3">会員ID</label>
        <label class="col-3"><%= @customer.id %></label>
      </div>
      <div class="form-group row">
        <%= f.label :氏名, class: "col-3" %>
          <%= f.text_field :last_name, class: "form-control col-3 mr-3" %>
          <%= f.text_field :first_name, class: "form-control col-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :フリガナ, class: "col-3" %>
        <%= f.text_field :last_name_kana, class: "form-control col-3 mr-3" %>
        <%= f.text_field :first_name_kana, class: "form-control col-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :post_code, '郵便番号', class: "col-3" %>
        <%= f.text_field :post_code, class: "form-control col-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :address, '住所', class: "col-3" %>
        <%= f.text_field :address, class: "form-control col-9" %>
      </div>

      <div class="form-group row">
        <%= f.label :phone_number, '電話番号', class: "col-3" %>
        <%= f.text_field :phone_number, class: "form-control col-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :email, 'メールアドレス', class: "col-3" %>
        <%= f.email_field :email, class: "form-control col-3" %>
      </div>

      <div class="form-gropu row">
        <%= f.label :is_deleted, '会員ステータス', class: "col-3" %>
        <div class="custom-control custom-radio">
          <%= f.radio_button :is_deleted, false %> <%= f.label :is_active, "有効", class:"mr-3 text-muted" %>
          <%= f.radio_button :is_deleted, true %> <%= f.label :is_active, "退会", class:"text-muted" %>
        </div>
      </div>

      <div class="actions mb-5 mt-5">
        <%= f.submit "変更を保存", class: "btn btn-success btn-lg col-2 offset-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="px-5 mx-5">
  <div class="mx-3"><h3 class="mb-5 mini-title">会員一覧</h3></div>
  <div class="row mx-5 px-5">

    <table class="table border-bottom">
      <thead class="thead-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <u><%= link_to customer.last_name+customer.first_name, admin_customer_path(customer), class:"text-dark" %></u>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td>
              <% if customer.active_for_authentication? %>
                <b class="text-success">有効</b>
              <% else %>
                <b class="text-muted">退会</b>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @customers, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/customers/show.html.erb
<div class="mb-2">
  <h3 class="ml-5 mini-title"><%= @customer.last_name+@customer.first_name %>さんの会員詳細</h3>
</div>

<div class="row mx-5">
  <table class="table mx-5 table-borderless col-5">
    <tbody>
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= @customer.last_name + "　" + @customer.first_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= @customer.last_name_kana + "　" + @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= @customer.post_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td>
          <% if @customer.active_for_authentication? %>
            <b class="text-success">有効</b>
          <% else %>
            <b class="text-muted">退会</b>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<div class="ml-5 mt-5">
  <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success mr-3" %>
</div>