config/routes.rb
Rails.application.routes.draw do

  # 顧客用

  scope module: :public do
    # customers
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    get "customers/my_page" => "customers#show"
    resource :customers, only: [:edit, :update]

    # homes
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    # items
    resources :items, only: [:index, :show]

    # cart_items
    delete "cart_items/all_destroy" => "cart_items#all_destroy"
    resources :cart_items, only: [:index, :update, :create, :destroy]

    # orders
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/finish' => 'orders#finish'
    resources :orders, only: [:index, :show, :new, :create]

    # addresses
    resources :addresses, only: [:index, :create, :destroy, :update, :edit]

  end

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



  # 管理者用

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # homes
    get '/' => 'homes#top'

    # cunstomers
    resources :customers, only: [:index, :show, :edit, :update]

    # items
    resources :items, except: [:destroy]

    # genres
    resources :genres, only: [:index, :create, :edit, :update]

    # orders
    resources :orders, only: [:show, :update]

    # order_details
    resources :order_details, only: [:update]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  validates :name, presence: true
  validates :post_code, presence: true, length: { is: 7 }
  validates :address, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing: 3, shipped: 4 }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order.shipping_cost = 800
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_status: params[:order][:order_status])
    if params[:order][:order_status] == "confirm_payment"
      @order.order_details.each do |order_detail|
        order_detail.update(making_status: "waiting_manufacture")
      end
    end
    redirect_to request.referer
  end

  private
  def order_params
    params.require(:order).permit(:order_status, :payment_method, :post_code, :address, :name, :shipping_cost, :customer_id, :total_payment)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="mini-title col-12 pb-4 mt-5"><strong>注文履歴詳細</strong></h3>
  </div>

  <div class="row">
    <div class="col-md-5">
      <table class="table">
        <tbody>
          <tr>
            <th>購入者</th>
            <th><%= @order.name %></th>
          </tr>
          <tr>
            <th>注文日</th>
            <th><%= @order.created_at.strftime('%Y/%m/%d') %></th>
          </tr>
          <tr>
            <th>配送先</th>
            <th>
              〒<%= @order.post_code %>
              <%= @order.address %><br>
              <%= @order.name %>
            </th>
          </tr>
          <tr>
            <th>支払方法</th>
            <th>
              <%= @order.payment_method_i18n %>
            </th>
          </tr>
          <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local: true do |f| %>
          <tr>
            <th>注文ステータス</th>
            <th>
              <%= f.select :order_status, Order.order_statuses_i18n.invert, class: "order_status" %>
              <%= f.submit "更新", class: "btn btn-success" %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>



    <div class="col-md-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.tax_included_price).to_s(:delimited) %>円</td>
            <td><%= order_detail.count %>　個</td>
            <td><%= (order_detail.item.tax_included_price*order_detail.count).to_s(:delimited) %>円</td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch, local: true do |f| %>
                <td><%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, class: "making_status" %></td>
                <td><%= f.submit "更新", class: "btn btn-success" %></td>
              <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>商品合計</th>
            <th><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %>円</th>
          </tr>
          <tr>
            <th>送料</th>
            <th><%= @order.shipping_cost %>円</th>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <th><%= @order.total_payment.to_s(:delimited) %>円</th>
         </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>