config/routes.rb
Rails.application.routes.draw do

  # 顧客用

  scope module: :public do
    # customers
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    get "customers/my_page" => "customers#show"
    resource :customers, only: [:edit, :update]

    # homes
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    # items
    resources :items, only: [:index, :show]

    # cart_items
    delete "cart_items/all_destroy" => "cart_items#all_destroy"
    resources :cart_items, only: [:index, :update, :create, :destroy]

    # orders
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/finish' => 'orders#finish'
    resources :orders, only: [:index, :show, :new, :create]

    # addresses
    resources :addresses, only: [:index, :create, :destroy, :update, :edit]

  end

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



  # 管理者用

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # homes
    get '/' => 'homes#top'

    # cunstomers
    resources :customers, only: [:index, :show, :edit, :update]

    # items
    resources :items, except: [:destroy]

    # genres
    resources :genres, only: [:index, :create, :edit, :update]

    # orders
    resources :orders, only: [:show, :update]

    # order_details
    resources :order_details, only: [:update]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :name, presence: true
  validates :post_code, presence: true, length: { is: 7 }
  validates :address, presence: true


  def address_display
    '〒' + post_code + '' + address + '' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :customer_id, :item_id, :total_count,  presence: true
  validates :total_count, numericality: { only_integer: true }

  def subtotal
    item.tax_included_price * total_count
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  # has_many :itmes, through: :cart_items
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :phone_number, presence: true
  validates :post_code, length: { is: 7 }
  # 退会済ユーザーをブロック
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def address_display_code
    '〒' + post_code + '' + address + '' + last_name + '' + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre

  with_options presence: true do
    validates :image
    validates :name
    validates :introduction
    validates :tax_excluded_price
    validates :sales_status
    validates :genre_id
  end

  validates :tax_excluded_price, numericality: {greater_than: 50}

  def tax_included_price
    (tax_excluded_price * 1.1).floor
  end

  enum sales_status: { sale: true, stop_selling: false }

  def get_item_image(size)
    image.variant(resize: size).processed
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  validates :name, presence: true
  validates :post_code, presence: true, length: { is: 7 }
  validates :address, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { impossible_manufacture: 0, waiting_manufacture: 1, manufacturing: 2,  finish: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = '商品を登録しました'
      redirect_to admin_item_path(@item)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = '商品の情報を更新しました'
      redirect_to admin_item_path(@item)
    else
      render 'edit'
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :tax_excluded_price, :sales_status, :genre_id, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
    keys: [
    :last_name,
    :first_name,
    :first_name_kana,
    :last_name_kana,
    :post_code,
    :address,
    :phone_number
    ])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "") %> 件のエラーが発生しました</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <ul>
      <li class="list-inline-item">
        <%= link_to do %>
          <i class="fab fa-instagram-square fa-2x social-btn"></i>
        <% end %>
      </li>
      <li class="list-inline-item">
        <%= link_to do %>
          <i class="fab fa-facebook-square fa-2x social-btn"></i>
        <% end %>
      </li>
      <li class="list-inline-item">
        <%= link_to do %>
          <i class="fab fa-twitter-square fa-2x social-btn"></i>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="row d-flex justify-content-center">
    <p>© 2022 ながのCAKE</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="shadow-sm p-3 mb-5 bg-body rounded">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand ", href="/">
        <%= image_tag 'logo6.png', class: 'icon' %>
      </a>
      <div class="px-5 text-light ">
        <% if customer_signed_in? %>
        ようこそ、<%= current_customer.last_name + current_customer.first_name %>さん！
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon "></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto d-block justify-content-end">
        <% if customer_signed_in? %>
          <li class="d-inline-block">
            <%= link_to customers_my_page_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            マイページ
            <% end %>
          </li>
          <li class="d-inline-block">
            <%=  link_to items_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            商品一覧
            <% end %>
          </li>
          <li class="d-inline-block">
            <%=  link_to cart_items_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            カート
            <% end %>
          </li>
          <li class="d-inline-block">
            <%= link_to destroy_customer_session_path, method: :delete, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            ログアウト
            <% end %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="d-inline-block">
            <%= link_to admin_items_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            商品一覧
            <% end %>
          </li>
          <li class="d-inline-block">
            <%=  link_to admin_customers_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            会員一覧
            <% end %>
          </li>
          <li class="d-inline-block">
            <%=  link_to admin_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            注文履歴一覧
            <% end %>
          </li>
          <li class="d-inline-block">
            <%=  link_to admin_genres_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            ジャンル一覧
            <% end %>
          </li>
          <li class="d-inline-block">
            <%= link_to destroy_admin_session_path, method: :delete, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="d-inline-block">
            <%= link_to items_path, class: "text-light border m-1 p-3 rounded font-weight-bold" do %>
            商品一覧
            <% end %>
          </li>
          <li class="d-inline-block">
            <%= link_to about_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            About
            <% end %>
          </li>
          <li class="d-inline-block">
            <%= link_to new_customer_registration_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            新規登録
            <% end %>
          </li>
          <li class="d-inline-block">
            <%= link_to new_customer_session_path, class: "text-light border m-1 p-3 rounded font-weight-bold"  do %>
            ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag 'application', :media => 'all' %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main>
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="col-12">
            <p id="notice"><%= notice %></p>
          </div>
        </div>
      </div>
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>